In [ ]:
# 1- Create a NumPy program to create a 3x3 identity matrix

import numpy as np

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 2- Create a NumPy program to generate 5 random number between 0 and 1

np.random.rand(5)

array([0.59538467, 0.18888634, 0.74884618, 0.01648997, 0.93654871])

In [ ]:
'''
3- Write a NumPy program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]
'''

np.hstack([np.array([10, 20, 30]), np.array([40, 50, 60, 70, 80, 90])])

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# 4- Write a NumPy program to create a 3X4 array and iterate over it using nditer.

arr3x4 = np.arange(12).reshape(3, 4)

for x in np.nditer(arr3x4):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
'''
5- Write a NumPy program to create a 1-D array then convert it into 2-
D array then print value and position for each value using
ndenumerate.
'''

for idx, val in np.ndenumerate(arr3x4):
    print(f'{idx}:  {val}')

(0, 0):  0
(0, 1):  1
(0, 2):  2
(0, 3):  3
(1, 0):  4
(1, 1):  5
(1, 2):  6
(1, 3):  7
(2, 0):  8
(2, 1):  9
(2, 2):  10
(2, 3):  11
